### ISSUE TITLE
Add yarn.lock to the project

### ISSUE THREAD

**Issue by quarian** [futurice/safer-globe-arms-report#34]
Currently, if you just run `yarn`, the system will generate a `yarn.lock` file for the local user. However, at least on my machine, the dependencies generated to the yarn.lock generate a non-functioning combination of node modules (and inspecting the `yarn.lock` file shows that some of the dependencies have been resolved to different versions than in the `package-lock.json`).

Forcing the dependencies of the releavant packages (d3 and the material ui packages) in `package.json` to be the same as they are in `package-lock.json` generates a functioning bundle - but it would certainly make sense if someone looks into this to check other dependencies to be current as well.

**Comment by chlif** [comment]
This issue was fixed in commit: https://github.com/futurice/safer-globe-arms-report/commit/11370d8d93b2d977eb3cc5a7060c961f96e671b9

**Comment by quarian** [comment]
Time to end this internal conflict.
